// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ToDoServices.API.Data;

#nullable disable

namespace ToDoServices.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20240530052318_lk")]
    partial class lk
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ToDoServices.API.Model.TodoTask", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsCompleted")
                        .HasColumnType("bit");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("TodoTasks");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "Description 1",
                            IsCompleted = false,
                            Title = "Task 1"
                        },
                        new
                        {
                            Id = 2,
                            Description = "Description 2",
                            IsCompleted = false,
                            Title = "Task 2"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Description 3",
                            IsCompleted = false,
                            Title = "Task 3"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
